import { useState, useEffect } from "react";
import Layout from "@/components/Layout";
import { motion, AnimatePresence } from "framer-motion";
import Head from "next/head";
import Image from "next/image";
import { Hexagon } from "@/components/Icons";
import { Pletter } from "@/components/Icons";
import profilePic from "../../public/images/profile/hacker2.gif";
import AnimatedText from "@/components/AnimatedText";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import NavBar from "@/components/NavBar";

export default function Home() {
  const [showLogo, setShowLogo] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setShowLogo(false);
    }, 4000);
  }, []);

  const [showNavBar, setShowNavBar] = useState(false);

  // After three seconds, show the NavBar
  setTimeout(() => {
    setShowNavBar(true);
  }, 3000);

  return (
    <>
      <Head>
        <title>Personal Website :)</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {showNavBar && <NavBar />}
      <main className="flex items-center text-dark w-full dark:text-yellow-400">
        {showLogo ? (
          <AnimatePresence>
            <div>
              <Hexagon />
              <Pletter />
            </div>
          </AnimatePresence>
        ) : (
          <>
            <Layout className="pt-4">
              <div className="flex items-center justify-between w-full">
                <motion.div
                  className="w-1/3 md:w-2/5 animate-wiggle"
                  initial={{ opacity: 0, y: -50, scale: 0.8 }}
                  animate={{
                    opacity: 1,
                    y: -20,
                    scale: 1,
                    transition: {
                      delay: 0.6,
                      duration: 1.5,
                      ease: [0.6, -0.05, 0.01, 0.9],
                    },
                  }}
                >
                  <div className="flex pt-14">
                    <Image
                      src={profilePic}
                      alt="CodeBucks"
                      priority={true}
                      sizes="(max-width: 768px) 100vw,
                    (max-width: 1200px) 50vw,
                    50vw"
                    />
                  </div>
                </motion.div>
                <div className="w-1/2 flex flex-col items-center self-center pt-14">
                  <AnimatedText
                    text="Hi there,"
                    className="!text-5xl !text-left"
                  />
                  <AnimatedText
                    text="I'm Parsa Peikani, a self-made software engineer :)"
                    className="!text-5xl !text-left"
                  />
                  <motion.p
                    className="my-4 text-base font-medium text-justify"
                    initial={{ opacity: 0, y: -20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 1, ease: "easeInOut" }}
                  >
                    {" "}
                    As a dedicated full-stack developer, I am passionate about
                    transforming ideas into cutting-edge web applications. I
                    invite you to explore my portfolio and projects, where you
                    can witness my expertise in React.js and web development.
                  </motion.p>
                  <div className="flex items-center self-start mt-2">
                    <motion.a
                      initial={{ opacity: 0, x: -80 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{
                        duration: 1,
                        ease: "easeInOut",
                        delay: 0.5,
                      }}
                      href="/dummy.pdf"
                      target={"_blank"}
                      className="flex items-center bg-dark dark:bg-yellow-400 text-light dark:text-dark p-2.5 px-6 rounded-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark hover:dark:bg-dark hover:dark:border-yellow-400 hover:dark:text-yellow-400"
                      download={true}
                    >
                      Resume <LinkArrow className={"w-6 ml-1"} />
                    </motion.a>
                    <motion.a
                      initial={{ opacity: 0, x: 80 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{
                        duration: 1,
                        ease: "easeInOut",
                        delay: 0.5,
                      }}
                      href="mailto:parsapeikani05@gmail.com"
                      target={"_blank"}
                      className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-yellow-400"
                    >
                      Contact
                    </motion.a>
                  </div>
                </div>
              </div>
            </Layout>
            <div className="pb-2">
              <HireMe />
            </div>
          </>
        )}
      </main>
    </>
  );
}
